Menuburger
WildCodeSchool/toulouse-0218-java-rateeverything pull request #1
Opened 2018-03-28 13:07 UTC by Boulzevard

création du menu burger

2018-03-28 14:22 UTC, CoraDel approved these changes

2018-03-28 16:47 UTC, bastienapp requested changes

2018-03-28 16:47 UTC, bastienwcs commented on app/src/main/res/layout/nav_header_menu.xml
> +        android:id="@+id/imageView"
Identifiant pas assez précis et pas en snake_case

2018-03-28 16:47 UTC, bastienwcs commented on app/src/main/res/layout/nav_header_menu.xml
> +        android:id="@+id/textView"
Identifiant pas assez précis et pas en snake_case

2018-03-28 16:47 UTC, bastienwcs commented on app/src/main/res/menu/activity_menu_drawer.xml
> +            android:title="Home" />
Pas de texte en dur (à modifier pour tous les title de ce layout)

2018-03-29 09:22 UTC, bastienapp approved these changes

2018-03-29 09:23 UTC, merged