Grid adapter user
WildCodeSchool/toulouse-0218-java-rateeverything pull request #13
Opened 2018-04-04 14:10 UTC by Sijey31

adpater , model de profil user

2018-04-04 14:19 UTC, Boulzevard commented on app/src/main/java/fr/wildcodeschool/rateeverything/ProfilUserActivity.java
> +
saut de ligne inutile

2018-04-04 14:19 UTC, Boulzevard commented on app/src/main/java/fr/wildcodeschool/rateeverything/ProfilUserActivity.java
> +
trop de saut de ligne

2018-04-05 09:44 UTC, bastienapp requested changes

2018-04-05 09:44 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/rateeverything/ProfilUserGridAdapter.java
> +        super(context,0,userGrid);
il manque un espace après chaque virgule

2018-04-05 09:44 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/rateeverything/ProfilUserGridAdapter.java
> +            convertView = LayoutInflater.from(getContext()).inflate(R.layout.item_grid_user, parent,false);
il manque un espace après parent,

2018-04-05 09:44 UTC, bastienwcs commented on app/src/main/res/layout/activity_user_photo.xml
> +        android:text="Commentaires"
Texte en dur

2018-04-05 09:50 UTC, Boulzevard approved these changes

2018-04-10 09:13 UTC, bastienapp approved these changes

2018-04-10 09:13 UTC, merged