Add photo
WildCodeSchool/toulouse-0218-java-rateeverything pull request #14
Opened 2018-04-04 14:20 UTC by CoraDel

Done add photo

2018-04-04 14:54 UTC, Boulzevard approved these changes
good for me

2018-04-04 15:05 UTC, bastienapp requested changes

2018-04-04 15:05 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/rateeverything/AddPhotoActivity.java
> +    Button buttonAdd;
pas besoin de faire de buttonAdd une variable membre.
Pour imagePhoto, elle doit se nommer mImagePhoto vu que c'est une variable membre

2018-04-04 15:05 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/rateeverything/AddPhotoActivity.java
> +        buttonAdd =(Button) findViewById(R.id.button_add_photo);
il manque un espace après le = sur les lignes 22 et 23

2018-04-05 10:04 UTC, bastienapp approved these changes

2018-04-05 10:04 UTC, merged