Architecture home
WildCodeSchool/toulouse-0218-java-rateeverything pull request #2
Opened 2018-03-28 13:08 UTC by CoraDel

creation page home

2018-03-28 16:45 UTC, bastienapp requested changes

2018-03-28 16:45 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/rateeverything/MainActivity.java
> +        try {
Mal indenté

2018-03-28 16:45 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/rateeverything/MainActivity.java
> +/*
Commentaire inutile à supprimer

2018-03-28 16:45 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/rateeverything/MainPhotoAdapter.java
> +        if(convertView==null)
Mal indenté

2018-03-28 16:45 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/rateeverything/MainPhotoAdapter.java
> +        TextView textusername = (TextView) convertView.findViewById(R.id.text_user_name_pub);
Nom de variable pas en camelCase

2018-03-28 16:45 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/rateeverything/MainPhotoAdapter.java
> +        TextView textdatepub = (TextView) convertView.findViewById(R.id.text_date_pub);
Nom de variable pas en camelCase

2018-03-28 16:45 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/rateeverything/MainPhotoAdapter.java
> +
Des retours à la lignes inutiles avant et après

2018-03-28 16:45 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/rateeverything/MainPhotoModel.java
> +
Retours à la ligne inutiles

2018-03-28 16:45 UTC, bastienwcs commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/listView_photo_main"
identifiant pas en snake_case

2018-03-28 16:45 UTC, bastienwcs commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/floatingActionButton_phto"
identifiant pas en snake_case

2018-03-28 16:45 UTC, bastienwcs commented on app/src/main/res/layout/item_photos.xml
> +        android:id="@+id/imagephoto"
Identifiant pas en snake_case

2018-03-28 16:45 UTC, bastienwcs commented on app/src/main/res/layout/item_photos.xml
> +
Saut de ligne inutile

2018-03-28 16:45 UTC, bastienwcs commented on app/src/main/res/layout/item_photos.xml
> +        android:text="TextView"
Pas de texte en dur, si c'est un texte temporaire, utiliser "tools:text"

2018-03-28 16:45 UTC, bastienwcs commented on app/src/main/res/layout/item_photos.xml
> +        tools:text="Date" />
Pas de texte en dur

2018-03-28 16:45 UTC, bastienwcs commented on app/src/main/res/layout/item_photos.xml
> +        tools:text="3" />
Pas de texte en dur, si c'est un texte temporaire, utiliser "tools:text"

2018-03-28 16:45 UTC, bastienwcs commented on app/src/main/res/layout/item_photos.xml
> +        android:id="@+id/ratingBar"
Identifiant pas en snake_case

2018-03-29 08:04 UTC, bastienapp requested changes

2018-03-29 08:04 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/rateeverything/MainPhotoAdapter.java
> +        if(convertView==null)
il manque des espaces autour du =, et avant la parenthèse

2018-03-29 08:04 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/rateeverything/MainPhotoAdapter.java
> +        Drawable drawablephoto = ContextCompat.getDrawable(getContext(), photoModel.getPhoto());
à mettre en camelCase

2018-03-29 08:04 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/rateeverything/MainPhotoAdapter.java
> +        note.setText(""+photoModel.getNote());
Utiliser String.valueOf()

2018-03-29 09:22 UTC, bastienapp requested changes
Vous avez oublié de modifier listView_photo_main en snake_case (ex: lv_photo_main ou listview_photo_main). Pensez à utiliser MAJ-F6 pour le modifier

2018-03-29 09:47 UTC, bastienapp requested changes

2018-03-29 09:47 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/rateeverything/MainPhotoAdapter.java
> +        if( convertView == null )
Non, il faut écrire ça :
if (convertView == null) {

2018-03-29 10:29 UTC, bastienapp approved these changes

2018-03-29 10:42 UTC, merged