biblithequeOkMaisPasAppPhotos
WildCodeSchool/toulouse-0218-java-rateeverything pull request #28
Opened 2018-04-19 14:52 UTC by CoraDel

Ok pour la bibliothque reliée à la Firebase mais pas pour l'app photo (a venir)

2018-04-19 15:41 UTC, bastienapp requested changes

2018-04-19 15:41 UTC, bastienapp commented on app/src/main/java/fr/wildcodeschool/rateeverything/AddPhotoActivity.java
> +    private Uri selectedImage = null;
Variable membre, des m partout à ajouter

2018-04-19 15:41 UTC, bastienapp commented on app/src/main/java/fr/wildcodeschool/rateeverything/AddPhotoActivity.java
> +/*
Pas de code "mort" dans une application, commentaires à supprimer

2018-04-19 15:41 UTC, bastienapp commented on app/src/main/java/fr/wildcodeschool/rateeverything/MainPhotoAdapter.java
> +     /*
commentaires à supprimer

2018-04-20 07:31 UTC, bastienapp approved these changes

2018-04-20 07:31 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/rateeverything/AddPhotoActivity.java
> +    private Uri selectedImage = null;
Variable membre, il faut des m devant tous ceux où il en manque

2018-04-20 07:31 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/rateeverything/AddPhotoActivity.java
> +                        Toast.makeText(AddPhotoActivity.this, "Ok", Toast.LENGTH_SHORT).show();
Texte en dur

2018-04-20 07:31 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/rateeverything/AddPhotoActivity.java
> +                        Toast.makeText(AddPhotoActivity.this, "Fail", Toast.LENGTH_SHORT).show();
Texte en dur

2018-04-20 07:31 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/rateeverything/AddPhotoActivity.java
> +/*
+1

2018-04-20 07:31 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/rateeverything/MainPhotoAdapter.java
> +     /*
+1

2018-04-20 07:31 UTC, bastienapp requested changes
à modifier

2018-04-20 07:51 UTC, CoraDel commented
j'ai crée une nouvelle branche avec une nouvelle Pull request, mon commit sur cette branche était bloquée

2018-04-20 07:55 UTC, closed without merging