création profil user et photo user
WildCodeSchool/toulouse-0218-java-rateeverything pull request #3
Opened 2018-03-28 13:11 UTC by Sijey31

Ajout du profil user et activity photo

2018-03-28 14:18 UTC, CoraDel approved these changes

2018-03-28 16:39 UTC, bastienapp requested changes

2018-03-28 16:39 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/rateeverything/MainActivity.java
> +        Button buttonprofiluser = findViewById(R.id.button_profil_user);
Le nom de variable n'est pas en camelCase (MAJ-F6)

2018-03-28 16:39 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/rateeverything/MainActivity.java
> +        Button buttonphotouser = findViewById(R.id.button_user_photo);
Le nom de variable n'est pas en camelCase (MAJ-F6)

2018-03-28 16:39 UTC, bastienwcs commented on app/src/main/java/fr/wildcodeschool/rateeverything/ProfilUserActivity.java
> +        ImageView imageView = (ImageView)findViewById(R.id.profil_photo_user);
Le nom de la variable n'est pas assez précis

2018-03-28 16:39 UTC, bastienwcs commented on app/src/main/res/layout/activity_main.xml
> +        android:text="Profil User"
Pas de textes en dur

2018-03-28 16:39 UTC, bastienwcs commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/Logo"
Nom d’identifiant pas assez précis et pas en snake_case

2018-03-28 16:39 UTC, bastienwcs commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/textView"
Nom d’identifiant pas assez précis et pas en snake_case

2018-03-28 16:39 UTC, bastienwcs commented on app/src/main/res/layout/activity_main.xml
> +        android:text="RATE EVERYTHING"
Pas de texte en dur

2018-03-28 16:39 UTC, bastienwcs commented on app/src/main/res/layout/activity_main.xml
> +        android:text="User photo"
Pas de texte en dur

2018-03-28 16:39 UTC, bastienwcs commented on app/src/main/res/layout/activity_profil_user.xml
> +        android:id="@+id/linearLayout"
Identifiant pas assez précis et pas en snake_case

2018-03-28 16:39 UTC, bastienwcs commented on app/src/main/res/layout/activity_profil_user.xml
> +
Espaces inutiles

2018-03-28 16:39 UTC, bastienwcs commented on app/src/main/res/layout/activity_user_photo.xml
> +        android:id="@+id/linearLayout2"
Nom d’identifiant pas assez précis et pas en snake_case

2018-03-28 16:39 UTC, bastienwcs commented on app/src/main/res/layout/activity_user_photo.xml
> +                android:id="@+id/imageView"
Nom d’identifiant pas assez précis et pas en snake_case

2018-03-28 16:39 UTC, bastienwcs commented on app/src/main/res/layout/activity_user_photo.xml
> +                android:id="@+id/textView5"
Nom d’identifiant pas assez précis et pas en snake_case

2018-03-28 16:39 UTC, bastienwcs commented on app/src/main/res/layout/activity_user_photo.xml
> +                android:id="@+id/ratingBar3"
Nom d’identifiant pas en snake_case

2018-03-28 16:39 UTC, bastienwcs commented on app/src/main/res/layout/activity_user_photo.xml
> +        android:id="@+id/ratingBar2"
Nom d’identifiant pas en snake_case

2018-03-28 16:39 UTC, bastienwcs commented on app/src/main/res/layout/activity_user_photo.xml
> +        android:id="@+id/textView3"
Nom d’identifiant pas assez précis et pas en snake_case

2018-03-28 16:39 UTC, bastienwcs commented on app/src/main/res/layout/activity_user_photo.xml
> +        android:id="@+id/constraintLayout"
Nom d’identifiant pas assez précis et pas en snake_case

2018-03-29 14:15 UTC, bastienapp approved these changes

2018-03-29 14:16 UTC, merged