Layout page login/create
WildCodeSchool/toulouse-0218-java-rateeverything pull request #5
Opened 2018-03-29 09:16 UTC by BenjaminBarret

Page login/create

2018-03-29 14:29 UTC, bastienapp requested changes
Tout modifier pour sortir le code de MainActivity et le mettre dans une nouvelle Activity

2018-03-30 09:17 UTC, bastienapp requested changes

2018-03-30 09:17 UTC, bastienwcs commented on app/src/main/res/layout/activity_login.xml
> +        tools:text="Create" />
Pas de texte en dur

2018-03-30 09:22 UTC, BenjaminBarret commented
Du coup, c'est modifié.

Le ven. 30 mars 2018 11:17, Bastien Krettly <notifications@github.com> a
écrit :

> *@bastienwcs* requested changes on this pull request.
> ------------------------------
>
> In app/src/main/res/layout/activity_login.xml
> <https://github.com/WildCodeSchool/toulouse-0218-java-rateeverything/pull/5#discussion_r178260802>
> :
>
> > +
> +    <Button
> +        android:id="@+id/button_valid_create"
> +        android:layout_width="wrap_content"
> +        android:layout_height="wrap_content"
> +        android:layout_marginBottom="8dp"
> +        android:layout_marginEnd="8dp"
> +        android:layout_marginStart="8dp"
> +        android:layout_marginTop="8dp"
> +        android:text="@string/create"
> +        android:visibility="gone"
> +        app:layout_constraintBottom_toBottomOf="parent"
> +        app:layout_constraintEnd_toEndOf="parent"
> +        app:layout_constraintStart_toStartOf="parent"
> +        app:layout_constraintTop_toTopOf="@+id/button_valid_login"
> +        tools:text="Create" />
>
> Pas de texte en dur
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/WildCodeSchool/toulouse-0218-java-rateeverything/pull/5#pullrequestreview-108295666>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/Ahn5E_vTFQ3khLaI6_xXGN9lcjJrQ1X5ks5tjfgjgaJpZM4TAAXc>
> .
>

2018-03-30 09:24 UTC, bastienapp approved these changes

2018-03-30 09:25 UTC, merged